### ISSUE TITLE
happy birthday uwu!

### ISSUE THREAD

**Issue by 5014f14r3** [ThatAquarel/CtmConverter#1]
pwease accept my fwiend wequest own chatuwbate, i didnt impwove youw code at aww, the onwy issue ive spotted iwt thawt uwu have a typo in the titwe. Its supposed tuwu be "cumconvewtew", isnt iwt? i stubwed acwoss thiws wepositowy because i too needed tuwu convewt a wot of stowen cum intwo wegaw c-men, but evew since i woved youw wowk, especiawwy youw youtube channew whewe uwu post epic bedwaws compiwations such as "think of you- a bedwaws montage"! i hope owne day uwu wiww be abwe tuwu dispway bad appwe own youw nitwogen coowed wego bwainstowm sex wobot.
 fwom the bottom of my heawt, i hope mowe of the nazi babyfuw community discovews youw awsome wowk! uwu nuzzwes uwu x3 youwe 14 now awnd thawt means youww get awwested if uwu duwu a biggie fuckie-wucky owo dont dwop the soapy woapy whewn uwu showew in jaiw ow youww get smexuawwy hawwased!  i wish uwu aww the awmond cummies fow thiws yeaw :3

seriously tho, this last month we have had a rlly bad hatred for eachother, and i suggest we, turn a new page for your 14th birthday. i apologize for the things ive done that have made you uncomfortable. as a show of good faith, ill delete voleurs de cum, and ill definitely stop making deepfakes of you. I just wanted to admit that i was definitely wrong about a lot of things, especially the livre toi incident. You should be allowed to remove your consent if the end result video make you feel uncomfortable and fucking making the vid public was petty and childish. Now i know you think that it will be like last time and ill meme about having "banned jokes" for a couple weeks before forgetting about this, but i have realilsed that making people uncomfortable.... is bad. mind blown, ikr. i hope we can go back to before edward some day.

**Comment by ThatAquarel** [comment]
nice, the pfp tho wtf is that
wtf
wtf
eduardo durante el tiempo del covid
